/**
 * Calibration set fixture — placeholder data shape matching the
 * `phase2_calibration` SQLite table from `scripts/run_phase2_calibration.py`.
 *
 * Lifecycle:
 *   1. Batch runner writes SQLite rows
 *   2. `python -m scripts.export_calibration` writes methodology-data.json
 *      next to this file.
 *   3. Frontend imports the JSON when present, falls back to FIXTURE
 *      otherwise.
 *
 * Once we migrate to Supabase, this file becomes a thin client-side cache
 * and the page fetches from `/api/methodology/calibration` instead.
 */
import calibrationJson from './methodology-data.json';

export type CalibrationLabel =
    | 'wrapper'
    | 'mid-glue'
    | 'senior-infra'
    | 'deep-tech'
    | 'edge-case';

export type DriftSeverity =
    | 'in_range'
    | 'soft_drift'    // within ±5 of expected range
    | 'hard_drift'    // >5 outside expected range — investigate
    | 'unknown';

export interface CalibrationRow {
    repo_url: string;
    audited_at: string;
    algo_version: string;
    hand_label: CalibrationLabel;
    expected_min: number;
    expected_max: number;
    hand_score: number;
    hand_notes: string;
    succeeded: boolean;
    repo_score: number | null;
    repo_tier: 'TIER_1_UI' | 'TIER_2_LOGIC' | 'TIER_3_DEEP' | null;
    discipline: string | null;
    in_range: boolean;
    delta_from_hand: number | null;
    drift_severity: DriftSeverity;
    claim_count: number;
    tier3_count: number;
    layer_capped_count: number;
    sdk_glue_capped_count: number;
    rule9_capped_count?: number;  // added in Phase 2.9; absent in older audits
    tradeoff_count: number;
    features_score: number | null;
    architecture_score: number | null;
    intent_score: number | null;
    forensics_score: number | null;
    total_ms: number;
}

/**
 * Placeholder fixture for the methodology page. Replace by exporting
 * from the SQLite DB once the calibration batch finishes.
 *
 * Run:
 *   python -m scripts.export_calibration_data > methodology-data.json
 *
 * (Export script TBD; for now this fixture lets us iterate on the page.)
 */
export const CALIBRATION_FIXTURE: CalibrationRow[] = [
    // First 2 real results from the in-flight batch — proof of shape
    {
        repo_url: 'https://github.com/sindresorhus/awesome',
        audited_at: '2026-05-01T20:31:18Z',
        algo_version: '582e3bb',
        hand_label: 'edge-case',
        expected_min: 0,
        expected_max: 35,
        hand_score: 15,
        hand_notes: 'A README list. Almost no code. Algo should handle gracefully.',
        succeeded: true,
        repo_score: 13,
        repo_tier: 'TIER_1_UI',
        discipline: 'Library/Framework/CLI',
        in_range: true,
        delta_from_hand: -2,
        drift_severity: 'in_range',
        claim_count: 0,
        tier3_count: 0,
        layer_capped_count: 0,
        sdk_glue_capped_count: 0,
        tradeoff_count: 0,
        features_score: 0,
        architecture_score: 0,
        intent_score: 5,
        forensics_score: 8,
        total_ms: 46525,
    },
    {
        repo_url: 'https://github.com/Textualize/rich',
        audited_at: '2026-05-01T20:34:00Z',
        algo_version: '582e3bb',
        hand_label: 'senior-infra',
        expected_min: 75,
        expected_max: 88,
        hand_score: 82,
        hand_notes: 'Terminal rendering library. Custom layout algorithms, ANSI parsing, progress rendering.',
        succeeded: true,
        repo_score: 95,
        repo_tier: 'TIER_3_DEEP',
        discipline: 'Library/Framework/CLI',
        in_range: false,
        delta_from_hand: 13,
        drift_severity: 'hard_drift',
        claim_count: 8,
        tier3_count: 1,
        layer_capped_count: 0,
        sdk_glue_capped_count: 0,
        tradeoff_count: 4,
        features_score: 32,
        architecture_score: 13,
        intent_score: 22,
        forensics_score: 18,
        total_ms: 176730,
    },
    // Remaining 18 will populate as the batch completes
];

/**
 * Live calibration data — generated by ``scripts/export_calibration.py``
 * from the latest SQLite results. Falls back to FIXTURE if the JSON file
 * is empty (eg. before the first export run).
 */
export const CALIBRATION_DATA: CalibrationRow[] =
    Array.isArray(calibrationJson) && calibrationJson.length > 0
        ? (calibrationJson as CalibrationRow[])
        : CALIBRATION_FIXTURE;

export const CALIBRATION_LABEL_META: Record<CalibrationLabel, {
    label: string;
    description: string;
    expectedRange: string;
    color: string;
    bgColor: string;
}> = {
    wrapper: {
        label: 'Wrapper',
        description: 'Simple utilities, single-purpose libraries. No engineering depth.',
        expectedRange: '40-55',
        color: 'text-zinc-700 dark:text-zinc-300',
        bgColor: 'bg-zinc-500/10 border-zinc-500/30',
    },
    'mid-glue': {
        label: 'Mid-Glue',
        description: 'Competent SDK orchestration. Real engineering, not novel algorithms.',
        expectedRange: '65-78',
        color: 'text-amber-700 dark:text-amber-400',
        bgColor: 'bg-amber-500/10 border-amber-500/30',
    },
    'senior-infra': {
        label: 'Senior Infra',
        description: 'Production-grade systems with real operational maturity.',
        expectedRange: '75-88',
        color: 'text-blue-700 dark:text-blue-400',
        bgColor: 'bg-blue-500/10 border-blue-500/30',
    },
    'deep-tech': {
        label: 'Deep Tech',
        description: 'Novel algorithms, distributed primitives, compiled-language depth.',
        expectedRange: '85-95',
        color: 'text-emerald-700 dark:text-emerald-400',
        bgColor: 'bg-emerald-500/10 border-emerald-500/30',
    },
    'edge-case': {
        label: 'Edge Case',
        description: 'Algo robustness checks. Repos where naive scoring would fail.',
        expectedRange: 'varies',
        color: 'text-violet-700 dark:text-violet-400',
        bgColor: 'bg-violet-500/10 border-violet-500/30',
    },
};

export const DRIFT_META: Record<DriftSeverity, { emoji: string; label: string; color: string }> = {
    in_range: {
        emoji: '✓',
        label: 'In range',
        color: 'text-emerald-600 dark:text-emerald-400',
    },
    soft_drift: {
        emoji: '~',
        label: 'Soft drift (within ±5)',
        color: 'text-amber-600 dark:text-amber-400',
    },
    hard_drift: {
        emoji: '!',
        label: 'Hard drift (>5)',
        color: 'text-rose-600 dark:text-rose-400',
    },
    unknown: {
        emoji: '?',
        label: 'Failed / unknown',
        color: 'text-muted-foreground',
    },
};
