/**
 * Fixture PersonScore data for the /p/[username] page.
 *
 * Mirrors the shape of compute_person_aggregation() output from
 * devproof_ranking_algo/person_score.py. Real backend wiring (Phase 4.5b)
 * will fetch this via /api/profile/[username].
 *
 * Two example profiles — one "real engineer" (Dhruv-style) and one
 * "Sindre Sorhus-style" high-reach-low-depth — so the dual-axis story
 * is immediately visible.
 */

import type { PersonScore } from './types/person-output';

// ─── Dhruv-style senior engineer ─────────────────────────────────────────────

export const FIXTURE_DHRUV: PersonScore = {
    schema_version: 'person.v1.0',
    formula_version: 'person_score.v1.0',
    computed_at: '2026-05-01T22:00:00Z',
    github_username: 'dhruv0206',
    person_score: 78,
    reach_score: 32,
    insufficient_data: false,
    person_breakdown: {
        weighted_score_sum: 312.4,
        weight_sum: 4.0,
        repo_count_total: 27,
        repo_count_included: 7,
        repo_count_skipped: 20,
        top_repo_url: 'https://github.com/dhruv0206/dev-proof-portfolio-open-source-search',
    },
    reach_breakdown: {
        total_stars: 23,
        total_forks: 4,
        total_dependents: null,
        popular_repo_count: 0,
    },
    primary_language: 'TypeScript',
    primary_discipline: 'Fullstack (Web)',
    cohort_key: null,
    cohort_percentile: null,
    cohort_size: null,
    repos: [
        {
            repo_url: 'https://github.com/dhruv0206/dev-proof-portfolio-open-source-search',
            repo_score: 82,
            repo_tier: 'TIER_2_LOGIC',
            authorship_percent: 100,
            age_years: 0.5,
            stars: 18,
            forks: 2,
            dependent_count: null,
            primary_language: 'TypeScript',
            discipline: 'Fullstack (Web)',
            is_owner: true,
            last_commit_at: '2026-05-01T18:00:00Z',
            weight_authorship: 1.0,
            weight_recency: 0.86,
            weight_impact: 0.27,
            weight_combined: 0.23,
            skipped: false,
            skip_reason: null,
        },
        {
            repo_url: 'https://github.com/Nenyax-AI/Nenyax',
            repo_score: 73,
            repo_tier: 'TIER_2_LOGIC',
            authorship_percent: 95,
            age_years: 0.4,
            stars: 7,
            forks: 2,
            dependent_count: null,
            primary_language: 'TypeScript',
            discipline: 'Backend/Systems',
            is_owner: true,
            last_commit_at: '2026-04-22T16:47:00Z',
            weight_authorship: 0.95,
            weight_recency: 0.89,
            weight_impact: 0.18,
            weight_combined: 0.15,
            skipped: false,
            skip_reason: null,
        },
        {
            repo_url: 'https://github.com/dhruv0206/Clawckathon',
            repo_score: 68,
            repo_tier: 'TIER_2_LOGIC',
            authorship_percent: 100,
            age_years: 0.1,
            stars: 1,
            forks: 1,
            dependent_count: null,
            primary_language: 'TypeScript',
            discipline: 'Fullstack (Web)',
            is_owner: true,
            last_commit_at: '2026-04-25T12:00:00Z',
            weight_authorship: 1.0,
            weight_recency: 0.97,
            weight_impact: 0.10,
            weight_combined: 0.10,
            skipped: false,
            skip_reason: null,
        },
        {
            repo_url: 'https://github.com/dhruv0206/jokes-app',
            repo_score: 55,
            repo_tier: 'TIER_1_UI',
            authorship_percent: 100,
            age_years: 0.1,
            stars: 0,
            forks: 0,
            dependent_count: null,
            primary_language: 'JavaScript',
            discipline: 'Fullstack (Web)',
            is_owner: true,
            last_commit_at: '2026-04-23T10:00:00Z',
            weight_authorship: 1.0,
            weight_recency: 0.97,
            weight_impact: 0.10,
            weight_combined: 0.10,
            skipped: false,
            skip_reason: null,
        },
        {
            repo_url: 'https://github.com/dhruv0206/Hackathon-5',
            repo_score: 60,
            repo_tier: 'TIER_2_LOGIC',
            authorship_percent: 100,
            age_years: 0.2,
            stars: 0,
            forks: 0,
            dependent_count: null,
            primary_language: 'TypeScript',
            discipline: 'Fullstack (Web)',
            is_owner: true,
            last_commit_at: '2026-04-15T09:00:00Z',
            weight_authorship: 1.0,
            weight_recency: 0.94,
            weight_impact: 0.10,
            weight_combined: 0.09,
            skipped: false,
            skip_reason: null,
        },
        // ... shortened for brevity; UI handles "+ N more skipped" gracefully
    ],
};

// ─── Sindre-Sorhus-style high-reach-low-depth ─────────────────────────────────

export const FIXTURE_SINDRESORHUS: PersonScore = {
    schema_version: 'person.v1.0',
    formula_version: 'person_score.v1.0',
    computed_at: '2026-05-01T22:00:00Z',
    github_username: 'sindresorhus',
    person_score: 56,
    reach_score: 96,
    insufficient_data: false,
    person_breakdown: {
        weighted_score_sum: 220.1,
        weight_sum: 3.95,
        repo_count_total: 1100,
        repo_count_included: 5,
        repo_count_skipped: 1095,
        top_repo_url: 'https://github.com/sindresorhus/got',
    },
    reach_breakdown: {
        total_stars: 580_000,
        total_forks: 71_000,
        total_dependents: null,
        popular_repo_count: 47,
    },
    primary_language: 'JavaScript',
    primary_discipline: 'Library/Framework/CLI',
    cohort_key: null,
    cohort_percentile: null,
    cohort_size: null,
    repos: [
        {
            repo_url: 'https://github.com/sindresorhus/awesome',
            repo_score: 13,
            repo_tier: 'TIER_1_UI',
            authorship_percent: 80,
            age_years: 8.5,
            stars: 461_000,
            forks: 58_000,
            dependent_count: null,
            primary_language: null,
            discipline: 'Library/Framework/CLI',
            is_owner: true,
            last_commit_at: '2025-11-10T12:00:00Z',
            weight_authorship: 0.80,
            weight_recency: 0.10,  // hits floor (8.5 years old)
            weight_impact: 1.00,   // capped (461K stars)
            weight_combined: 0.40, // weight cap fires (max 40% of total)
            skipped: false,
            skip_reason: null,
        },
        {
            repo_url: 'https://github.com/sindresorhus/got',
            repo_score: 85,
            repo_tier: 'TIER_2_LOGIC',
            authorship_percent: 80,
            age_years: 6.0,
            stars: 14_000,
            forks: 1_000,
            dependent_count: null,
            primary_language: 'TypeScript',
            discipline: 'Library/Framework/CLI',
            is_owner: true,
            last_commit_at: '2026-03-15T10:00:00Z',
            weight_authorship: 0.80,
            weight_recency: 0.17,
            weight_impact: 0.79,
            weight_combined: 0.11,
            skipped: false,
            skip_reason: null,
        },
        {
            repo_url: 'https://github.com/sindresorhus/np',
            repo_score: 70,
            repo_tier: 'TIER_2_LOGIC',
            authorship_percent: 80,
            age_years: 5.0,
            stars: 8_000,
            forks: 200,
            dependent_count: null,
            primary_language: 'JavaScript',
            discipline: 'Library/Framework/CLI',
            is_owner: true,
            last_commit_at: '2025-12-01T14:00:00Z',
            weight_authorship: 0.80,
            weight_recency: 0.22,
            weight_impact: 0.74,
            weight_combined: 0.13,
            skipped: false,
            skip_reason: null,
        },
        {
            repo_url: 'https://github.com/sindresorhus/p-limit',
            repo_score: 78,
            repo_tier: 'TIER_2_LOGIC',
            authorship_percent: 90,
            age_years: 4.0,
            stars: 2_000,
            forks: 80,
            dependent_count: null,
            primary_language: 'JavaScript',
            discipline: 'Library/Framework/CLI',
            is_owner: true,
            last_commit_at: '2025-11-20T09:00:00Z',
            weight_authorship: 0.90,
            weight_recency: 0.30,
            weight_impact: 0.63,
            weight_combined: 0.17,
            skipped: false,
            skip_reason: null,
        },
        {
            repo_url: 'https://github.com/sindresorhus/chalk',
            repo_score: 72,
            repo_tier: 'TIER_2_LOGIC',
            authorship_percent: 70,
            age_years: 12.0,
            stars: 22_000,
            forks: 900,
            dependent_count: null,
            primary_language: 'JavaScript',
            discipline: 'Library/Framework/CLI',
            is_owner: true,
            last_commit_at: '2025-10-15T08:00:00Z',
            weight_authorship: 0.70,
            weight_recency: 0.10,  // floor
            weight_impact: 0.83,
            weight_combined: 0.06,
            skipped: false,
            skip_reason: null,
        },
    ],
};

export const FIXTURE_PROFILES: Record<string, PersonScore> = {
    dhruv0206: FIXTURE_DHRUV,
    sindresorhus: FIXTURE_SINDRESORHUS,
};
